version: '3.8'

services:
  web:
    build: .
    command: wait-for db:5432 -- python run.py --no-uvicorn-debug
    volumes:
      - ./app/:/home/izyan/app/
      - ./media:/home/izyan/media
      - static_volume:/home/izyan/staticfiles
    env_file:
      - ./.env
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:15.1
    environment:
      POSTGRES_DB: izyan
      POSTGRES_USER: izyan
      POSTGRES_PASSWORD: izyan
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:1.23-alpine
    restart: unless-stopped
    ports:
      - 8000:80
      - 443:443
    environment:
      - DOMAIN
    volumes:
      - static_volume:/home/izyan/staticfiles
      - ./media:/home/izyan/media
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/certbot:/var/www/certbot
    depends_on:
      - web
    env_file:
      - ./.env

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email ${EMAIL} --agree-tos --no-eff-email
      -d ${DOMAIN}
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/certbot:/var/www/certbot

volumes:
  postgres_data:
  static_volume:
